name: 'Close stale issues and PR'

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GIT_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 5 days with no activity. Remove the stale label or comment or this will be closed in 2 days'
        stale-pr-message: 'This PR is stale because it has been open 5 days with no activity. Remove the stale label or comment or this will be closed in 2 days'
        days-before-stale: 4
        days-before-close: 2
